defaults: &pg_nine
  working_directory: ~/workspace
  docker:
    - image: circleci/postgres:9.5-alpine
      environment:
      - POSTGRES_USER: postgres
      - POSTGRES_DB: temporal_tables_test

defaults: &pg_ten
  working_directory: ~/workspace
  docker:
    - image: circleci/postgres:10-alpine
      environment:
      - POSTGRES_USER: postgres
      - POSTGRES_DB: temporal_tables_test

version: 2
jobs:
  run-test-nine:
    <<: *pg_nine
    steps:
      - checkout
      - run: sh test/runTest.sh

  run-test-nochecks-nine:
    <<: *pg_nine
    steps:
      - checkout
      - run: sh test/runTestNochecks.sh

  run-test-ten:
    <<: *pg_ten
    steps:
      - checkout
      - run: sh test/runTest.sh

  run-test-nochecks-ten:
    <<: *pg_ten
    steps:
      - checkout
      - run: sh test/runTestNochecks.sh

workflows:
  version: 2
  tests:
    jobs:
      - run-test-nine
      - run-test-nochecks-nine
      - run-test-ten
      - run-test-nochecks-ten