defaults: &pg_nine
  working_directory: ~/workspace
  docker:
    - image: circleci/node:latest
    - image: circleci/postgres:9.5-alpine
      environment:
      - POSTGRES_USER: root
      - POSTGRES_DB: db

defaults: &pg_ten
  working_directory: ~/workspace
  docker:
    - image: circleci/node:latest
    - image: circleci/postgres:10-alpine
      environment:
      - POSTGRES_USER: root
      - POSTGRES_DB: db

version: 2
jobs:
  build-nine:
    <<: *pg_nine
    steps:
      - checkout

  build-ten:
    <<: *pg_nine
    steps:
      - checkout

  run-test-nine:
    <<: *pg_nine
    steps:
      - run: make run_test

  run-test-nochecks-nine:
    <<: *pg_nine
    steps:
      - run: make run_test_nochecks

  run-test-ten:
      <<: *pg_ten
      steps:
        - run: make run_test

  run-test-nochecks-ten:
    <<: *pg_ten
    steps:
      - run: make run_test_nochecks

workflows:
  version: 2
  tests:
    jobs:
      - build-nine
      - build-ten
      - run-test-nine:
          requires:
            - build-nine
      - run-test-nochecks-nine:
          requires:
            - build-nine
      - run-test-ten:
          requires:
            - build-ten
      - run-test-nochecks-ten:
          requires:
            - build-ten